version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Configuração do Nginx
      - ./nginx_logs:/var/log/nginx  # Logs do Nginx (opcional)
    networks:
      - webnet

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Dados persistentes do MySQL
      - ./public/dump:/docker-entrypoint-initdb.d/  # Scripts de inicialização do MySQL
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "juliana"
      MYSQL_PASSWORD: "admin"
    networks:
      - webnet

volumes:
  db_data:
  nginx_logs:

networks:
  webnet:
    driver: bridge
